class LabError(Exception): ...
class ScenarioNotFound(LabError): ...
class ProviderError(LabError): ...
class ModuleLoadError(LabError): ...
class ScoringError(LabError): ...
class ToolSandboxError(LabError): ...
class ConfigError(LabError): ...
class RAGError(LabError): ...
